name: Auto Update Worker

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 1 * * *" # 每天UTC时间凌晨1点运行
  workflow_dispatch:
    inputs:
      update_latest:
        description: '是否手动更新 Latest 正式版？'
        required: false
        default: false
        type: boolean

env:
  TZ: "Asia/Shanghai"  # 设置时区，便于理解执行时间

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置环境变量
        id: vars
        run: |
          # 获取当前版本
          if [ -f version.txt ]; then
            echo "local_version=$(cat version.txt)" >> $GITHUB_OUTPUT
          else
            echo "local_version=" >> $GITHUB_OUTPUT
          fi
          
          # 获取发布信息
          API_URL="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases"
          RESPONSE=$(curl -s "$API_URL")
          
          # 最新 Pre-release
          PRE_RELEASE=$(echo "$RESPONSE" | jq -r '[.[] | select(.prerelease==true)][0]')
          PRE_TAG=$(echo "$PRE_RELEASE" | jq -r '.tag_name // ""')
          PRE_DOWNLOAD=$(echo "$PRE_RELEASE" | jq -r '.assets[] | select(.name=="worker.zip") | .browser_download_url // ""')
          
          # 最新正式版
          LATEST_RELEASE=$(echo "$RESPONSE" | jq -r '[.[] | select(.prerelease==false)][0]')
          LATEST_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name // ""')
          
          echo "pre_tag=$PRE_TAG" >> $GITHUB_OUTPUT
          echo "pre_download=$PRE_DOWNLOAD" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: 显示版本信息
        run: |
          echo "当前版本: ${{ steps.vars.outputs.local_version || '无' }}"
          echo "最新 Pre-release: ${{ steps.vars.outputs.pre_tag || '无' }}"
          echo "最新正式版: ${{ steps.vars.outputs.latest_tag || '无' }}"

      - name: 手动更新 Latest
        if: ${{ github.event.inputs.update_latest == 'true' && steps.vars.outputs.latest_tag }}
        run: |
          echo "开始手动更新到 Latest: ${{ steps.vars.outputs.latest_tag }}"
          # 获取下载链接
          API_URL="https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/tags/${{ steps.vars.outputs.latest_tag }}"
          RESPONSE=$(curl -s "$API_URL")
          DOWNLOAD_URL=$(echo "$RESPONSE" | jq -r '.assets[] | select(.name=="worker.zip") | .browser_download_url')
          
          # 清理并更新文件
          find . -maxdepth 1 -not -name '.git' -not -name '.' -exec rm -rf {} + 2>/dev/null || true
          wget -q -O worker.zip "$DOWNLOAD_URL"
          unzip -q -o worker.zip
          rm worker.zip
          echo "${{ steps.vars.outputs.latest_tag }}" > version.txt

      - name: 自动更新 Pre-release
        if: ${{ github.event.inputs.update_latest != 'true' && steps.vars.outputs.pre_tag && steps.vars.outputs.local_version != steps.vars.outputs.pre_tag }}
        run: |
          echo "发现新 Pre-release: ${{ steps.vars.outputs.pre_tag }}"
          # 清理并更新文件
          find . -maxdepth 1 -not -name '.git' -not -name '.' -exec rm -rf {} + 2>/dev/null || true
          wget -q -O worker.zip "${{ steps.vars.outputs.pre_download }}"
          unzip -q -o worker.zip
          rm worker.zip
          echo "${{ steps.vars.outputs.pre_tag }}" > version.txt

      - name: 提交更新
        if: ${{ success() && (steps.vars.outputs.local_version != steps.vars.outputs.pre_tag || github.event.inputs.update_latest == 'true') }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |
            ${{ github.event.inputs.update_latest == 'true' && format('🔄 手动更新 Latest: {0}', steps.vars.outputs.latest_tag) || format('🔄 自动更新 Pre-release: {0}', steps.vars.outputs.pre_tag) }}
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
